name: Deploy CTPortal App

on:
  push:
    branches:
      - master  # change this if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Install Composer dependencies
      run: composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/sites/22b/5/5afc26cef4/public_html/portal # 👈 Update this to your actual Laravel folder path on the server
          git pull origin master
          php artisan migrate --force
          php artisan config:cache
